from pydoc2md import main

# main(
#     "/Users/federicoclaudi/Documents/Github/BrainRender/brainrender",
#     "/Users/federicoclaudi/Documents/Github/brainrender-docs/autogenerated-docs/docs",
#     githuburl="https://github.com/BrancoLab/BrainRender/tree/brainglobeintegration",
# )

main("pydoc2md", "Docs", githuburl="https://github.com/FedeClaudi/pydoc2md")
